### ISSUE TITLE
Adapter not found

### ISSUE THREAD

**Issue by ghost** [edgexfoundry/device-bluetooth#27]
I tried starting the bluetooth device microservice, its not able to connect to the pygatt server. 

docker logs show the below output : 
```
Attaching to edgex-device-bluetooth
edgex-device-bluetooth | Adapter not found, trying alternative
```

~ ps -ef | grep pygatt
```
root 13782 13730 0 16:36 ? 00:00:00 /bin/sh /edgex/edgex-device-bluetooth/bluetooth.sh device-bluetooth.jar -Djava.security.egd=file:/dev/urandom -Xmx100M /edgex/edgex-resource-pygatt/virtualenv/bin/FlaskController.py 5000
root 13784 13782 6 16:36 ? 00:00:21 python /edgex/edgex-resource-pygatt/virtualenv/bin/FlaskController.py -p 5000
root1 15071 2966 0 16:42 pts/1 00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn pygatt
```

COMPLETE LOGS => [logs.txt](https://github.com/edgexfoundry/device-bluetooth/files/2257587/logs.txt)

If i try to perform a BLE scan using **hcitool** it runs without problem. So i think i can exclude any hardware or driver problems.

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
